version: "3.8"

services:

  accounts:
    image: is3x/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ls3-network

  loans:
    image: is3x/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ls3-network

  cards:
    image: is3x/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - ls3-network

networks:
  ls3-network: